---
# URL for download repository install file for Ubuntu. Tested on Ubuntu Server 22.04. You can get this URL on this page - https://www.zabbix.com/download in "Zabbix Packages" section.
zabbix_repo_package_url_ubuntu: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb

# URL for download repository install file for CentOS 7. You can get this URL on this page - https://www.zabbix.com/download in "Zabbix Packages" section.
zabbix_repo_package_url_centos7: https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-release-6.0-4.el7.noarch.rpm

# URL for download repository install file for CentOS 9. You can get this URL on this page - https://www.zabbix.com/download in "Zabbix Packages" section.
zabbix_repo_package_url_centos9: https://repo.zabbix.com/zabbix/6.0/rhel/9/x86_64/zabbix-release-6.0-4.el9.noarch.rpm

# IP Address of Zabbix Server
zabbix_server_ip: 10.10.10.44